version: '2'

services:
  mongodb:
    container_name: ebisc-mongodb
    image: centos/mongodb-32-centos7
    environment:
      - MONGODB_USER=ebisc
      - MONGODB_PASSWORD=${DB_PASS}
      - MONGODB_DATABASE=ebisc
      - MONGODB_ADMIN_PASSWORD=${ADMIN_PASS}
    volumes:
      - /mnt/mongodb/data:/var/lib/mongodb/data:Z
  db_backups:
    build:
      context: .
      dockerfile: Dockerfile-db-backups
    container_name: ebisc-db-backups
    environment:
      - ST_AUTH=$ST_AUTH
      - ST_USER=$ST_USER
      - ST_KEY=$ST_KEY
      - MONGODB_PASSWORD=${DB_PASS}
    links:
      - mongodb
    depends_on:
      - mongodb
  webserver:
    build:
      context: .
      dockerfile: Dockerfile-webserver
    container_name: ebisc-webserver
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    command: tracker -dbpass ${DB_PASS}
  db_client:
    container_name: ebisc-mongodb-client
    image: centos/mongodb-32-centos7
    links:
      - mongodb
    command: mongo -u ebisc -p ${DB_PASS} mongodb/ebisc
    depends_on:
      - mongodb
  tracker:
    build:
      context: .
      dockerfile: Dockerfile-tracker
    container_name: ebisc-datatracker
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PASS=${DB_PASS}
      - MONGODB_USER=ebisc
      - HPSCREG_USER=${HPSCREG_USER}
      - HPSCREG_PASS=${HPSCREG_PASS}
      - IMS_USER=${IMS_USER}
      - IMS_PASS=${IMS_PASS}
    links:
      - mongodb
    depends_on:
      - mongodb
  npm:
    container_name: npm
    image: node:slim
    entrypoint: npm
    command: install --unsafe-perm
    volumes:
      - ./webcontent:/usr/src/app
    working_dir: /usr/src/app
    user: "1001"
