requires 'MongoDB';
requires 'Moose';
requires 'JSON';
requires 'LWP::UserAgent';
requires 'LWP::Protocol::https';
requires 'Time::Moment';
requires 'Text::Markdown';
requires 'namespace::autoclean';
