#!/bin/bash

set -e

function usage() {
  echo "Required environment variables:"
  echo "  AWS_ACCESS_KEY_ID"
  echo "  AWS_SECRET_ACCESS_KEY"
  echo "  AWS_ENDPOINT_URL"
  echo "  AWS_BUCKET"
  echo "  AWS_PREFIX"
  echo "Optional environment variables:"
  echo "  MONGODB_HOST      default mongodb"
  echo "  MONGODB_USER      default ebisc"
  echo "  MONGODB_PASSWORD  default ebisc"
  echo "  MONGODB_DATABASE  default ebisc"
  exit 1
}

# require parameters
if [ -z "$AWS_ACCESS_KEY_ID" ]; then usage; fi
if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then usage; fi
if [ -z "$AWS_ENDPOINT_URL" ]; then usage; fi
if [ -z "$AWS_BUCKET" ]; then usage; fi
if [ -z "$AWS_PREFIX" ]; then usage; fi

# set defaults
: ${MONGODB_HOST:=mongodb}
: ${MONGODB_USER:=ebisc}
: ${MONGODB_PASSWORD:=ebisc}
: ${MONGODB_DATABASE:=ebisc}

TIMESTAMP=`date +%F-%H-%M-%S`

mongodump -h $MONGODB_HOST -u $MONGODB_USER -p $MONGODB_PASSWORD -d $MONGODB_DATABASE

DUMP=mongodb-$MONGODB_DATABASE-$TIMESTAMP
echo $DUMP
mv dump "$DUMP"
tar -czf "$DUMP.tar.gz" "$DUMP"

aws --endpoint-url $AWS_ENDPOINT_URL s3 cp $DUMP.tar.gz s3://${AWS_BUCKET}/${AWS_PREFIX}/

EPOCH_DELETE=`date -d "-60 days" +"%s"`
IFS=$'\n'
for line in `aws --endpoint-url $AWS_ENDPOINT_URL s3 ls s3://${AWS_BUCKET}/${AWS_PREFIX}/`; do
  IFS=" " read DATE TIME SIZE OBJECT <<< "${line}"
  EPOCH_FILE=`date -d "$DATE $TIME" +"%s"`
  if [ $EPOCH_DELETE -ge $EPOCH_FILE ];
  then
    echo "Deleting expired object s3://${AWS_BUCKET}/${AWS_PREFIX}/${OBJECT}"
    aws --endpoint-url $AWS_ENDPOINT_URL s3 rm s3://${AWS_BUCKET}/${AWS_PREFIX}/${OBJECT}
  fi
done
