#!/bin/bash

set -e

function usage() {
  echo "Required environment variables:"
  echo "  ST_AUTH"
  echo "  ST_USER"
  echo "  ST_KEY"
  echo "Optional environment variables:"
  echo "  MONGODB_HOST      default mongodb"
  echo "  MONGODB_ADMIN_PASSWORD  default ebisc"
  echo "  MONGODB_DATABASE  default ebisc"
  exit 1
}

# require parameters
if [ -z "$ST_AUTH" ]; then usage; fi
if [ -z "$ST_USER" ]; then usage; fi
if [ -z "$ST_KEY" ]; then usage; fi

# set defaults
: ${MONGODB_HOST:=mongodb}
: ${MONGODB_ADMIN_PASSWORD:=ebisc}
: ${MONGODB_DATABASE:=ebisc}

NEWEST=`swift list trackerdumps --prefix mongodb-$MONGODB_DATABASE- | sort | tail -1`
echo newest file in swift is $NEWEST
swift download trackerdumps $NEWEST
tar -xzf $NEWEST
DBDIR=`basename $NEWEST .tar.gz`/$MONGODB_DATABASE

if [ ! -d "$DBDIR" ]; then
  echo "cannot backup: directory $DBDIR does not exist"
  exit 1
fi

mongo -u admin -p $MONGODB_ADMIN_PASSWORD $MONGODB_HOST/admin --eval "db.getSiblingDB('${MONGODB_DATABASE}').dropDatabase()"
mongorestore -h $MONGODB_HOST -u admin -p $MONGODB_ADMIN_PASSWORD -d $MONGODB_DATABASE $DBDIR
